services:
  - type: web
    name: aquabot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: STORMGLASS_API_KEY
        sync: false
      - key: MAPTILER_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: RATE_LIMIT_PER_MINUTE
        value: "100" 